use AdventureWorks2017
 
 SELECT DATENAME(YEAR, GETDATE())
 SELECT DATENAME(MONTH, GETDATE())
 SELECT DATENAME(DAY, GETDATE())
 SELECT DATENAME(HOUR, GETDATE())
 SELECT DATENAME(WEEKDAY, GETDATE())


SELECT 
	a.Name,
	a.SellStartDate,
	DATENAME(MONTH, a.SellStartDate) AS Mes
FROM
	Production.Product AS a
WHERE
	DATENAME(MONTH, a.SellStartDate)= DATENAME(MONTH, GETDATE())

--------------------------------------------------------------------------

 SELECT DATEPART(YEAR, GETDATE())
 SELECT DATEPART(MONTH, GETDATE())
 SELECT DATENAME(DAY, GETDATE())
 SELECT DATENAME(HOUR, GETDATE())
 SELECT DATENAME(WEEKDAY, GETDATE())
