-- SELECT GETDATE()
use AdventureWorks2017
 
SELECT DATEADD(MONTH, -1, GETDATE())
SELECT DATEADD(YEAR, 1, GETDATE())
SELECT DATEADD(MINUTE, 10, GETDATE())


SELECT
    *
FROM
    Production.Product AS a
WHERE
	CAST(a.SellStartDate AS date) BETWEEN '2012-05-30' AND DATEADD(YEAR, 1, '2012-05-30')
